config/routes.rb
Rails.application.routes.draw do

  resources :comments

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  resources :articles do
    resources :comments
  end

  root 'articles#index'

  resources :search

end

app/models/article.rb
class Article < ActiveRecord::Base

  has_many :comments

  attr_accessor :search
  # cattr_accessor :current
  # def to_param
  #   "#{id} #{title}".parameterize
  # end

  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders, :history]

  def slug_candidates
    [
        :title,
        [:title, :id]
    ]
  end



  has_attached_file :photo

  validates :title, :presence => true,
            :length => { :maximum => 50}
  validates :caption, :presence => true
  validates :matter, :presence => true

  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']



end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource

  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # before_filter :set_current_account

  # def set_current_account
  #   #  set @current_account from session data here
  #   @curr_user = current_user.email
  #   Article.current = @curr_user
  # end

  # GET /articles
  # GET /articles.json
  def index

      @search = Article.search(params[:q])

    # @articles = Article.all
    #   @curr_user = current_user.email
    #   puts "-----------------#{@curr_user}"
          if user_signed_in?
            @article = Article.new
            @articles = Article.all.page(params[:page]).per(2)
          else
            @articles = Article.all.page(params[:page]).per(3)
          end

        @articles  = @search.result.page(params[:page]).per(3)

  end
    # puts @articles
  # GET /articles/1
  # GET /articles/1.json
  def show
    @search = Article.search(params[:q])
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html
      format.pdf do
        pdf = ShowPdf.new(@article)
        send_data pdf.render, type: "application/pdf"
      end
    end

  end
  # GET /articles/new
  def new
    @search = Article.search(params[:q])

    if user_signed_in?
      @article = Article.new
    else
      redirect_to new_user_session_path
    end
  end

  # GET /articles/1/edit
  def edit

    @search = Article.search(params[:q])

    if user_signed_in?
    else
      redirect_to new_user_session_path
    end
  end

  # POST /articles
  # POST /articles.json
  def create
    @search = Article.search(params[:q])
    @article = Article.new(article_params)
    respond_to do |format|
      if @article.save && @article.update_attributes(:email => current_user.email )
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    @search = Article.search(params[:q])

    if user_signed_in?
      respond_to do |format|
        if @article.update(article_params)
          format.html { redirect_to @article, notice: 'Article was successfully updated.' }
          format.json { render :show, status: :ok, location: @article }
        else
          format.html { render :edit }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to new_user_session_path
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @search = Article.search(params[:q])

    if user_signed_in?
      @article.destroy
      respond_to do |format|
        format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to new_user_session_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :caption, :matter, :photo, :search)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article, :html => {:multipart => true} do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :caption %><br>
    <%= f.text_field :caption %>
  </div>
  <div class="field">
    <%= f.label :matter %><br>
    <%= f.text_area :matter, :id => "message_area", :cols => 50, :rows => 20 %>
  </div>

    <div class="field">
     <%= f.file_field :photo %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/_header.html.erb
<nav class="navbar navbar-default" role="navigation" style="height:55px">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if user_signed_in? %>
        <a class="navbar-brand" href="\">Hi <%= current_user.email %></a>
      <% else %>
        <%= link_to 'Login', new_user_session_path, :class => "navbar-brand" %>
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if user_signed_in? %>
      <ul class="nav navbar-nav">
        <li><%= link_to 'Sign Out', destroy_user_session_path, :method => 'delete' %></br></li>
        <li><%= link_to 'New Article', new_article_path %></br></li>
      </ul>
      <% else %>
          <ul class="nav navbar-nav">
            <li><%= link_to 'Home', articles_path , :class => "navbar-brand"%></br></li>
          </ul>
      <% end %>

      <div class="col-sm-6 col-md-6 pull-right">

      <div class = "navbar-form navbar-right" role = "search">
        <div class="input-group">
        <%= search_form_for @search do |f| %>
            <div class="field" style="float:left;">
              <%= f.text_field :matter_or_caption_or_title_cont,:class => "form-control", :placeholder => "Search"  %>
            </div>
            <div class="input-group-btn"">
              <%= f.submit "Search", :class=> "btn btn-default" %>
            </div>
        <% end %>
        </div>
      </div>
      </div>
    </div>
  </nav>

app/views/articles/edit.html.erb
<%= render 'header' %>

<div class="container">
  <h1>Edit Note</h1>
    <%= form_for @article, :html => {:multipart => true} do |f| %>

        <% if @article.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

              <ul>
                <% @article.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="form-group">
          <%= f.label :title %><br>
          <%= f.text_field :title, :class => "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :caption %><br>
          <%= f.text_field :caption, :class => "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :matter %><br>
          <%= f.text_area :matter, :class => "form-control", :id => "message_area", :cols => 50, :rows => 20 %>
        </div>

        <div class="field">
          <%= f.file_field :photo, class: 'btn btn-default' %>
        </div>

        <div class="input-group-btn">
          <div class="actions">
            <%= f.submit "Save" , class: 'btn btn-large' %>
          </div>

    <% end %>

    <div class="input-group-btn">
      <%= link_to 'Back', articles_path %>
      <div class="input-group-btn">
</div>

app/views/articles/index.html.erb
<%= render 'header' %>


<body>
<div class = "container">
  <%= paginate @articles%>
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <div class = "container">
    <div class = "row">
      <thead>
        <tr>
          <th class ="span1">S.NO.</th>
          <th class ="span3"><%= model_class.human_attribute_name(:title) %></th>
          <th class ="span3"><%= model_class.human_attribute_name(:caption) %></th>
          <th class ="span3"><%= model_class.human_attribute_name(:created_at) %></th>
        </tr>
      </thead>
      </div>
  </div>
  <tbody>
  <% i = 1
     # @curr_user = current_user.email
  %>

  <% if user_signed_in? %>
    <% @articles.where(email: current_user.email).order(created_at: :desc).each do |article|  %>
      <tr>
        <td class ="span1"><%= i %></td>
        <td class ="span3"><%= link_to article.title, article_path(article)%></td>
        <td class ="span3"><%= article.caption %></td>
        <td class ="span3"><%=l article.created_at %></td>
        <td>
          <% i = i + 1%>
          <%= link_to "PDF", article_path(article, format: "pdf"), :class => 'btn btn-default btn-xs' %>

        <% if can? :update, article %>
             <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_article_path(article), :class => 'btn btn-default btn-xs' %>
          <% end %>
          <% if can? :destroy, article %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      article_path(article),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>

    <% @articles.where.not(email: current_user.email).order(created_at: :desc).each do |article|  %>
      <tr>
        <td class ="span1"><%= i %></td>
        <td class ="span3"><%= link_to article.title, article_path(article)%></td>
        <td class ="span3"><%= article.caption %></td>
        <td class ="span3"><%=l article.created_at %></td>
        <td>
          <% i = i + 1%>
          <%= link_to "PDF", article_path(article, format: "pdf"), :class => 'btn btn-default btn-xs' %>
          <% if can? :update, article %>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_article_path(article), :class => 'btn btn-default btn-xs' %>
          <% end %>
          <% if can? :destroy, article %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          article_path(article),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-xs btn-danger' %>
          <% end %>
        </td>
      </tr>
  <% end %>
  <% else %>
      <% @articles.order(created_at: :desc).each do |article|  %>
          <tr>
            <td class ="span1"><%= i %></td>
            <td class ="span3"><%= link_to article.title, article_path(article)%></td>
            <td class ="span3"><%= article.caption %></td>
            <td class ="span3"><%=l article.created_at %></td>
            <td>
              <% i = i + 1%>
              <%= link_to "PDF", article_path(article, format: "pdf"), :class => 'btn btn-default btn-xs' %>
              <% if can? :update, article %>
                  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                              edit_article_path(article), :class => 'btn btn-default btn-xs' %>
              <% end %>
              <% if can? :destroy, article %>
                  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                              article_path(article),
                              :method => :delete,
                              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                              :class => 'btn btn-xs btn-danger' %>
              <% end %>
            </td>
          </tr>
      <% end %>
  <%end%>



  </tbody>
</table>
<% if can? :create, Article %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_article_path,
            :class => 'btn btn-default' %>
      <% end %>

<div>

</body>

app/views/articles/new.html.erb
<%= render 'header' %>

<div class="container">
  <h1>New Note</h1>
    <%= form_for @article, :html => {:multipart => true} do |f| %>

        <% if @article.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

              <ul>
                <% @article.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="form-group">
          <%= f.label :title %><br>
          <%= f.text_field :title, :class => "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :caption %><br>
          <%= f.text_field :caption, :class => "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :matter %><br>
          <%= f.text_area :matter, :class => "form-control", :id => "message_area", :cols => 50, :rows => 20 %>
        </div>

        <div class="field">
          <%= f.file_field :photo, class: 'btn btn-default' %>
        </div>
        <div class="input-group-btn">
        <div class="actions">
          <%= f.submit "Save" , class: 'btn btn-large' %>
        </div>

    <% end %>

    <div class="input-group-btn">
      <%= link_to 'Back', articles_path %>
      <div class="input-group-btn">
</div>

app/views/articles/show.html.erb
<%= render 'header' %>

<div class="container">
    <!--<p id="notice"><%= notice %></p>-->
    <strong><h2 class="form-signin-heading"><%= @article.title %></h2></strong>

    <p"><%= @article.caption %></p>

    <%= image_tag @article.photo.url %></br></br>

    <p  style="margin-right: 300px; line-height: 200%"><%= @article.matter %>
    </p>

  <div class="container" style = "margin-bottom: 50px">
    <% if can? :update, @article %>
         <%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-default' %>
    <% end %>
    <%= link_to 'Back', articles_path, class: 'btn btn-default' %>
    </div>

  <h2>Comments</h2>
  <table class="table table-striped">
    <div class = "container">
    <tbody>
      <% @article.comments.each do |comment| %>
              <tr>
                <td class ="span2"><strong><%= comment.commenter %> :</strong></td>
                <td class ="span2"><%= comment.body %></td>
                <% if can? :update, comment %>
                <td class="span2"><%= link_to 'Edit', edit_article_comment_path(comment.article, comment) %></td></br></br>
                  <% end %>
                <% if can? :destroy, comment %>
                    <td class="span2"><%= link_to 'Delete', [comment.article, comment], method: :delete , data: { confirm: 'Are you sure?' }%></td></br></br>
                <% end %>
              </tr>
      <% end %>
    </tbody>
    <div class = "container">
    </table>


  <h3>Add a comment:</h3>
  <div style="width: 50%">
  <%= form_for([@article, @article.comments.build]) do |f| %>
      <p>
        <%= f.label :commenter %><br>
        <%= f.text_field :commenter,:class => "form-control" %>
      </p>
      <p>
        <%= f.label :body %><br>
        <%= f.text_area :body, :class => "form-control" %>
      </p>
      <p>
        <%= f.submit "Comment", :class => "btn btn-default" %>
      </p>
     </div>
  <% end %>

</div>